spring:
  application:
    name: transaction-service
  config:
    import: "optional:configserver:http://localhost:8088"
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:9090/realms/microservices/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: microservices-admin
            client-secret: GaMOPLfQq69uwdZwHOlewqKKioCu2UZS
            authorization-grant-type: client_credentials
