server:
  port: 8060

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/microservices
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/accounts/**

        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/transactions/**

        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/api/email/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**