server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_transactions
    username: root
    password: 1234

rabbitmq:
  exchange:
    name: microservices-exchange
  queues:
    email: emails
    accounts: accounts
  routing:
    email-key: email-key
    accounts-key: accounts-key