server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_transactions
    username: root
    password: 1234
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/microservices
      client:
        provider:
          keycloak:
            token-uri: http://localhost:9090/realms/microservices/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: microservices-admin
            client-secret: GaMOPLfQq69uwdZwHOlewqKKioCu2UZS
            authorization-grant-type: client_credentials